services:
  beatnik:
    container_name: "beatnik-dev"
    image: "nickseman/beatnik:dev"
    volumes:
      - "./docker/library.db:/app/library.db"
      - "./docker/library:/app/library"
    env_file: .env
    environment:
      - LIBRARY_PATH=/app/library
      - DATABASE_URL=file:/app/library.db
    restart: no
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src

        - action: rebuild
          path: package.json
          target: /app
