services:
  beatnik:
    container_name: "beatnik-next-local"
    image: "nickseman/beatnik:next"
    volumes:
      - "./docker/library.db:/library.db"
      - "./docker/library:/library"
    env_file: .env
    environment:
      - LIBRARY_PATH=/library
      - DATABASE_URL=file:/library.db
    restart: no
    build:
      context: .
      dockerfile: Dockerfile
