services:
  beatnik-dev:
    container_name: beatnik-dev
    platform: linux/amd64
    image: nickseman/beatnik:dev
    build:
      context: .
      target: dev
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
      - ./docker/library.db:/app/library.db
      - ./docker/library:/app/library
    env_file: .env
    environment:
      - LIBRARY_PATH=/app/library
      - DATABASE_URL=file:/app/library.db
