# fly.toml app configuration file generated for beatnik on 2024-01-15T18:55:15-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "beatnik"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[mounts]
  source="beatnik_data"
  destination="/data"
