# fly.toml app configuration file generated for beatnik on 2024-01-15T18:55:15-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "beatnik"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

[mounts]
  source="beatnik_data"
  destination="/data"
