name: (RELEASE) Docker Hub
on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: (RELEASE) Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: nickseman/beatnik:latest
          cache-from: type=registry,ref=nickseman/beatnik:buildcache
          cache-to: type=registry,ref=nickseman/beatnik:buildcache,mode=max
