name: CI release
on:
  push:
    branches: [release]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy.key
          sudo chmod 600  ~/.ssh/deploy.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.LIGHTSAIL_SSH_PRIVATE_KEY}}
          SSH_KNOWN_HOSTS: ${{secrets.LIGHTSAIL_SSH_KNOWN_HOSTS}}

      - name: Install PM2
        run: npm i pm2

      - name: Deploy
        run: npm run deploy
